sudo: false

language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run lint
  - npm run nsp
  - npm run cover
  - make install

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules

addons:
   code_climate:
     repo_token: $CODECLIMATE_REPO_TOKEN

after_success:
  - npm run codeclimate-cover-submit
